application: kingsfordsmithscouts2015
version: 35
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /default.aspx
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static/

